version 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/blog-front
    overwirte: yes
hooks:
  ApplicationStop:
    - location: script/stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: script/start.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: script/clean.sh
      timeout: 60
      runas: root
